# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Taesun Yeoum
tagline:          'The personal website of Taesun Yeoum'
url:              http://tsyoum.github.io
paginate:         1
baseurl:          http://tsyoum.github.io/poole/
author:
  name:           'Taesun Yeoum'
  url:            https://twitter.com/mdo
  email:          tsyoum@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/tsyoum/poole
