# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Taesun Yeoum
tagline:          'The personal website of Taesun Yeoum'
url:              http://tsyoum.github.io
paginate:         2
baseurl:          /
author:
  name:           'Taesun Yeoum'
  url:            http://tsyoum.github.io/
  email:          tsyoum@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           github.com/tsyoum/tsyoum.github.io

pages_list:       { 'About':'/about', 'Archive':'/archive' }
